ClusterDomain: cluster.local
common:
  image:
    repository: quay.io/pires/docker-elasticsearch-kubernetes
    tag: 5.6.1
    pullPolicy: Always

  # Defines the service type for all outward-facing (non-discovery) services.
  serviceType: NodePort

  env:
    CLUSTER_NAME: "ctec-elasticsearch"
    # Uncomment this if you get the "No up-and-running site-local (private)
    # addresses" error.
    # NETWORK_HOST: "_eth0_"

# Client/ingest nodes can execute pre-processing pipelines, composed of
# one or more ingest processors. Depending on the type of operations performed
# by the ingest processors and the required resources, it may make sense to
# have dedicated ingest nodes, that will only perform this specific task.
client:
  # It isn't common to need more than 2 client nodes.
  replicas: 2
  antiAffinity: "soft"
  env:
    NODE_DATA: "false"
    NODE_MASTER: "false"
    NODE_INGEST: "true"
    HTTP_ENABLE: "true"
    ES_JAVA_OPTS: "-Xms8096m -Xmx8096m"

# Data nodes hold the shards that contain the documents you have indexed. Data
# nodes handle data related operations like CRUD, search, and aggregations. 
# These operations are I/O-, memory-, and CPU-intensive. It is important to 
# monitor these resources and to add more data nodes if they are overloaded.
#
# The main benefit of having dedicated data nodes is the separation of the 
# master and data roles.
dashboards:
  - kubernetes-overview-dashboard
  - kubernetes-dashboard
data:
  # This count will depend on your data and computation needs.
  replicas: 2
  antiAffinity: "soft"
  env:
    NODE_DATA: "true"
    NODE_MASTER: "false"
    NODE_INGEST: "false"
    HTTP_ENABLE: "false"
    ES_JAVA_OPTS: "-Xms8096m -Xmx8096m"

  # If enabled, then the data nodes will be StatefulSets with associated
  # persistent volume claims.
  stateful:
    enabled: true

    # This will fill quickly in production. You will want to increase it.
    size: 12Gi

    # The PVC storage class. On AWS "gp2" would be appropriate.
    class: "default"

# The master node is responsible for lightweight cluster-wide actions such as
# creating or deleting an index, tracking which nodes are part of the 
# cluster, and deciding which shards to allocate to which nodes. It is 
# important for cluster health to have a stable master node.
master:
  # Master replica count should be (#clients / 2) + 1, and generally at least 3.
  replicas: 3
  antiAffinity: "soft"
  env:
    NODE_DATA: "false"
    NODE_MASTER: "true"
    NODE_INGEST: "false"
    HTTP_ENABLE: "false"
    ES_JAVA_OPTS: "-Xms8096m -Xmx8096m"

    # The default value for this environment variable is 2, meaning a cluster
    # will need a minimum of 2 master nodes to operate. If you have 3 masters
    # and one dies, the cluster still works.
    NUMBER_OF_MASTERS: "2"

curator:
  enabled: true
  schedule: "0 1 * * *"

  # Allows modification of the default age-based filter. If you require more
  # sophisticated filtering, modify the action file specified in
  # templates/es-curator-config.yaml.
  age:
    timestring: "%Y.%m.%d"
    unit: "days"
    unit_count: 3

service:
  kibana:
    name: kibana
  elasticsearch:
    name: elasticsearch
  httpPort: 9200
  transportPort: 9300

kibana:
  enabled: true
  replicas: 1
  image:
    repository: cfontes/kibana-xpack-less
    tag: 5.5.0
    pullPolicy: Always
  httpPort: 80
  resources:
    limits:
      cpu: 4000m
    requests:
      cpu: 500m
  env:
    #SERVER_BASEPATH: "/api/v1/proxy/namespaces/default/services/kibana"
    XPACK_GRAPH_ENABLED: "false"
    XPACK_ML_ENABLED: "false"
    XPACK_REPORTING_ENABLED: "false"
    XPACK_SECURITY_ENABLED: "false"
  ingress:
    enabled: false
    # Used to create an Ingress record.
    hosts:
      # - kibana.local
    annotations:
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    tls:
      # Secrets must be manually created in the namespace.
      # - secretName: kibana-tls
      #   hosts:
      #     - kibana.local
